# Docker Image をビルドして ghcr にpushする 
name: docker-server 

on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
    paths: 
      - src/main/java/** 
      - server.build.gradle 
      - Dockerfile 

env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs: 
  build: 
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs. 
      id-token: write 
    
    strategy:
      matrix: 
        include: 
          - name: MusicalChairs-server
            file: Dockerfile
            target: release  

    steps: 
      - name: checkout
        uses: actions/checkout@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to registry 
        uses: docker/login-action@v1 
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Downcase DOCKER_REPO
        run: |
          github_repo="${{ github.repository }}"
          echo "DOCKER_REPO=${github_repo,,}" >> "${GITHUB_ENV}"
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_REPO }}/${{ matrix.name }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=branch
            type=sha,format=long
      
      - name: Build and Push image 
        uses: docker/build-push-action@v2 
        with: 
          context: .
          push: ${{ github.actor != 'dependabot[bot]' }}
          file: ${{ matrix.file }}
          target: ${{ matrix.target }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          